---
- name: Install firewalld
  ansible.builtin.apt:
    name: firewalld
    state: present

#####################################################################
# NOTE: Using default "public" firewalld zone

- name: Allow SSH
  ansible.builtin.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Allow HTTP
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Allow HTTPS
  ansible.builtin.firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Allow TeamViewer
  ansible.builtin.firewalld:
    port: 5938/tcp
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Allow NTP (Chrony)
  ansible.builtin.firewalld:
    service: ntp
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Allow DNS
  ansible.builtin.firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: true
    zone: public

#####################################################################

- name: Get current firewalld settings
  ansible.builtin.command:
    cmd: firewall-cmd --list-all
  register: firewalld_settings

- name: Show firewalld settings
  ansible.builtin.debug:
    msg: "{{ firewalld_settings.stdout_lines }}"
