---
allow_duplicates: true
galaxy_info:
  author: Ismet Handzic
  description: Role for simply rebooting the system and waiting for it
  company: Logic Lift Solutions, LLC
  min_ansible_version: "2.14"
  license: Proprietery
  platforms:
    - name: Ubuntu
