---
- name: Install Chrony package
  apt:
    name: chrony
    state: latest
    update_cache: true

- name: Copy Chrony configuration file
  copy:
    src: "{{ role_path }}/files/chrony.conf"
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"

- name: Restart and enable Chrony service
  systemd:
    name: chrony
    state: restarted
    enabled: true
