---
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Copy Fail2Ban configuration jail file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/jail.local"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fail2Ban

- name: Ensure Fail2Ban is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
